### ISSUE TITLE
Fix stem highlighting with Verovio 3.14

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#253]
The work around for the scaling bug in Firefox introduced as small highlighting issue. Stems are no longer highlighted.

![image](https://user-images.githubusercontent.com/689412/211812462-73da2b66-753a-4586-8f8d-ccfd5b0a6c54.png)

The CSS should be changed from
```css
{ fill: red; }
```
to
```css
{ fill: red; color: red; }
```
